/*  ----------------------------------------------------------------<Prolog>-
    Name:       iafemaildb.h
    Title:      dotBEER Email Daemon Database Access

    Generated by eslservice at 2003/02/19 11:49:23

    Synopsis:   Get data from email log and email queue

    This program is copyright (c) 1991-2001 iMatix Corporation.
    ---------------------------------------------------------------</prolog>-*/
#ifndef _IAFEMAILDB_INCLUDED__
#define _IAFEMAILDB_INCLUDED__

/*- Record structure --------------------------------------------------------*/

typedef struct
{
    long   dbid;
    long   dbsender;
    char   dbrecipients [50 + 1];
    char   dbsubject [150 + 1];
    char   dbbody [8000 + 1];
    long   dbstatus;
    char   dbmessage [8000 + 1];
    double dbsentat;
    double dbcreatedts;
} IAFEMAILLOG;

typedef struct
{
    long   dbid;
    double dbsendat;
    long   dbemaillogid;
    double dbrevisedts;
} IAFEMAILQUEUE;

/*- Function declaration ----------------------------------------------------*/

#ifdef __cplusplus
extern "C" {
#endif

Bool  iafemail_connect        (char *name, char *user, char *pwd);
void  iafemail_disconnect     (void);
char *iafemail_error_message  (void);
int   iafemaillog_update      (IAFEMAILLOG  *record);
int   iafemaillog_get         (IAFEMAILLOG  *record);
long  iafemailqueue_get_all   (double timestamp, IAFEMAILQUEUE **record);
int   iafemailqueue_delete    (IAFEMAILQUEUE *record);


#ifdef __cplusplus
}
#endif

#endif
