/*  ----------------------------------------------------------------<Prolog>-
    Name:       usemaildb.h
    Title:      UltraSource Email Daemon Database Access

    Generated by eslservice at 2003/02/19 11:49:18

    Synopsis:   Get data from email log and email queue

    This program is copyright (c) 1991-2001 iMatix Corporation.
    ---------------------------------------------------------------</prolog>-*/
#ifndef _USEMAILDB_INCLUDED__
#define _USEMAILDB_INCLUDED__

/*- Record structure --------------------------------------------------------*/

typedef struct
{
    long   usid;
    long   uscustomerid;
    long   ususergroupid;
    long   usorderid;
    char   uscontext [50 + 1];
    long   ussender;
    char   usrecipients [255 + 1];
    char   ussubject [150 + 1];
    char   usfromaddr [255 + 1];
    char   usreplyaddr [255 + 1];
    long   usstatus;
    double ussentat;
    double uscreatedts;
    char   usbody [8000 + 1];
    char   usmessage [8000 + 1];
} USEMAILLOG;

typedef struct
{
    long   usid;
    double ussendat;
    long   usemaillogid;
    double usrevisedts;
} USEMAILQUEUE;

/*- Function declaration ----------------------------------------------------*/

#ifdef __cplusplus
extern "C" {
#endif

Bool  usemail_connect         (char *name, char *user, char *pwd);
void  usemail_disconnect      (void);
char *usemail_error_message   (void);
int   usemaillog_update       (USEMAILLOG   *record);
int   usemaillog_get          (USEMAILLOG   *record);
long  usemailqueue_get_all    (double timestamp, USEMAILQUEUE **record);
int   usemailqueue_delete     (USEMAILQUEUE *record);


#ifdef __cplusplus
}
#endif

#endif
