/*  ----------------------------------------------------------------<Prolog>-
    Name:       usemailudb.h
    Title:      UltraSource Unicode Email Daemon Database Access

    Generated by eslservice at 2003/03/18 16:58:27

    Synopsis:   Get data from email log and email queue

    This program is copyright (c) 1991-2001 iMatix Corporation.
    ---------------------------------------------------------------</prolog>-*/
    
#ifndef _USEMAILUDB_INCLUDED__
#define _USEMAILUDB_INCLUDED__

/*- Record structure --------------------------------------------------------*/

typedef struct
{
    long   usid;
    long   ussender;
    UCODE  usrecipients [255 + 1];
    UCODE  usfromaddr   [255 + 1];
    UCODE  usreplyaddr  [255 + 1];
    UCODE  ussubject    [150 + 1];
    UCODE  usbody       [4000 + 1];
    long   usstatus;
    UCODE  usmessage    [4000 + 1];
    double ussentat;
    long   uscodepage;
    UCODE  uscharset    [50 + 1];
    double uscreatedts;
} USEMAILULOG;

typedef struct
{
    long   usid;
    double ussendat;
    long   usemaillogid;
    double usrevisedts;
} USEMAILUQUEUE;

/*- Function declaration ----------------------------------------------------*/

#ifdef __cplusplus
extern "C" {
#endif

Bool  usemailu_connect        (char *name, char *user, char *pwd);
void  usemailu_disconnect     (void);
char *usemailu_error_message  (void);
int   usemailulog_update      (USEMAILULOG  *record);
int   usemailulog_get         (USEMAILULOG  *record);
long  usemailuqueue_get_next  (double timestamp, USEMAILUQUEUE *record);
int   usemailuqueue_delete    (USEMAILUQUEUE *record);


#ifdef __cplusplus
}
#endif

#endif
